---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pl94xbsja6em/public_html/
    - /bin/cp home.html $DEPLOYPATH
    - /bin/cp css/style.css $DEPLOYPATH/css/
    - /bin/cp balls.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp src/* $DEPLOYPATH/src/
    - /bin/cp static/* $DEPLOYPATH/static/
    - /bin/cp static/imgs/* $DEPLOYPATH/static/imgs/
    - /bin/cp static/imgs/cyclegan.jpeg $DEPLOYPATH/static/imgs/cyclegan.jpeg
    - /bin/cp static/imgs/forceseat.png $DEPLOYPATH/static/imgs/forceseat.png
    - /bin/cp static/imgs/MRIscans.png $DEPLOYPATH/static/imgs/MRIscans.png
    - /bin/cp -R build/* $DEPLOYPATH/build/
    - /bin/cp -R node_modules/* $DEPLOYPATH/node_modules/
    - /bin/cp Resume_MilesMilosevich.pdf $DEPLOYPATH
