---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pl94xbsja6em/public_html/
    - /bin/cp home.html $DEPLOYPATH
    - /bin/cp css/style.css $DEPLOYPATH/css/
    - /bin/cp balls.html $DEPLOYPATH
    - /bin/cp src/balls2.js $DEPLOYPATH/src/